<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZRFy4zN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZRFy4zN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZRFy4zN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZRFy4zN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZRFy4zN\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZRFy4zN',
    'container.build_id' => '6a909e2a',
    'container.build_time' => 1652966200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZRFy4zN');
